export const spacesData = [
  {
    id: 1,
    categories: ["Nails", "Spa"],
    image: "/spaces/space-1.jpg",
    date: "2025",
    name: "Tomy Rivero Beauty Lab",
    location: "Inwood, NYC",
    clientImage: "/spaces/client-1.jpeg",
    clientName: "Tomy Rivero Beauty",
    route: "/sample-space",
  },
  {
    id: 2,
    categories: ["Nails", "Skincare"],
    image: "/spaces/space-2.jpg",
    date: "2025",
    name: "Tomy Rivero Beauty Lab",
    location: "Inwood, NYC",
    clientImage: "/spaces/client-2.jpeg",
    clientName: "Tomy Rivero Beauty",
    route: "/sample-space",
  },
  {
    id: 3,
    categories: ["Nails", "Gallery"],
    image: "/spaces/space-3.jpg",
    date: "2025",
    name: "Tomy Rivero Beauty Lab",
    location: "Inwood, NYC",
    clientImage: "/spaces/client-3.jpeg",
    clientName: "Tomy Rivero Beauty",
    route: "/sample-space",
  },
  {
    id: 4,
    categories: ["Gallery", "Skincare"],
    image: "/spaces/space-4.jpg",
    date: "2025",
    name: "Tomy Rivero Beauty Lab",
    location: "Inwood, NYC",
    clientImage: "/spaces/client-4.jpeg",
    clientName: "Tomy Rivero Beauty",
    route: "/sample-space",
  },
  {
    id: 5,
    categories: ["Spa", "Nails"],
    image: "/spaces/space-5.jpg",
    date: "2025",
    name: "Tomy Rivero Beauty Lab",
    location: "Inwood, NYC",
    clientImage: "/spaces/client-5.jpeg",
    clientName: "Tomy Rivero Beauty",
    route: "/sample-space",
  },
  {
    id: 6,
    categories: ["Skincare", "Spa"],
    image: "/spaces/space-6.jpg",
    date: "2025",
    name: "Tomy Rivero Beauty Lab",
    location: "Inwood, NYC",
    clientImage: "/spaces/client-6.jpeg",
    clientName: "Tomy Rivero Beauty",
    route: "/sample-space",
  },
  {
    id: 7,
    categories: ["Nails", "Skincare", "Spa"],
    image: "/spaces/space-7.jpg",
    date: "2025",
    name: "Tomy Rivero Beauty Lab",
    location: "Inwood, NYC",
    clientImage: "/spaces/client-7.jpeg",
    clientName: "Tomy Rivero Beauty",
    route: "/sample-space",
  },
];
